# Generated by Django 5.2.5 on 2025-09-17 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_routine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_treino', models.CharField(max_length=100)),
                ('dias_semana', models.PositiveIntegerField()),
                ('objetivo', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_exercicio', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=20)),
                ('repeticoes', models.CharField(max_length=20)),
                ('descanso', models.CharField(help_text='Tempo de descanso entre as séries', max_length=50)),
                ('grupo_muscular', models.CharField(max_length=50)),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='fitness_routine.treino')),
            ],
        ),
    ]
