# Generated by Django 5.2.1 on 2025-09-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_routine', '0002_treino_exercicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dia_semana',
            field=models.CharField(blank=True, choices=[('Segunda-feira', 'Segunda-feira'), ('Terça-feira', 'Terça-feira'), ('Quarta-feira', 'Quarta-feira'), ('Quinta-feira', 'Quinta-feira'), ('Sexta-feira', 'Sexta-feira'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=20, null=True),
        ),
    ]
